version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=${DEBUG}
      - CLOUDINARY_URL= ${CLOUDINARY_URL}
      - DEFAULT_FILE_STORAGE = ${DEFAULT_FILE_STORAGE} 
      - AWS_STORAGE_BUCKET_NAME = ${AWS_STORAGE_BUCKET_NAME} 
      - AWS_S3_ENDPOINT_URL = ${AWS_S3_ENDPOINT_URL}
      - AWS_S3_ACCESS_KEY_ID = ${WS_S3_ACCESS_KEY_ID}
      - AWS_S3_SECRET_ACCESS_KEY = ${WS_S3_SECRET_ACCESS_KEY}
      - AWS_S3_SIGNATURE_VERSION = ${AWS_S3_SIGNATURE_VERSION}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    restart: always

