# Generated by Django 4.2.10 on 2024-02-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_category_description_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
