# Generated by Django 4.2.10 on 2024-02-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
